name: Sync CVAT Helm Chart

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync-charts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo (Helm Chart Repo)
      uses: actions/checkout@v2
      with:
        path: 'helm-chart-repo'

    - name: Checkout external repo (CVAT)
      uses: actions/checkout@v2
      with:
        repository: 'armagankaratosun/cvat'
        ref: 'v2.24.0'  # Specify the branch, tag, or commit here
        path: 'cvat-repo'

    - name: Copy CVAT Helm Charts
      run: |
        mkdir -p helm-chart-repo/cvat
        cp -R cvat-repo/helm-chart/* helm-chart-repo/cvat/
        rm -rf helm-chart-repo/cvat/analytics

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Update Helm dependencies
      run: |
        cd helm-chart-repo/cvat
        helm dependency update

    - name: Package CVAT Helm Charts
      run: |
        cd helm-chart-repo/cvat
        helm package .

    - name: Re-index Helm Repository
      run: |
        cd helm-chart-repo
        helm repo index . --url https://awesome-helm-charts.github.io/

    - name: Commit and Push Changes
      run: |
        cd helm-chart-repo
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'
        git add .
        git commit -m 'Update Helm charts [skip ci]'
        git push

